name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: Tag (e.g. 2.1.1. If set, publishes new containers)
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - alpine
          - android-armv7
          - android-arm64
          - centos7-devtoolset7
          - linux-x86
          - linux-armv6
          - linux-armv7
          - linux-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ghcr.io/node-usb/${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.event.inputs.tag != '' }}
            type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          push: ${{ github.event.inputs.tag != '' }}
          tags: ${{ steps.meta.outputs.tags }}
